### ISSUE TITLE
unwanted extra space between username and content

### ISSUE THREAD

**Issue by frankli0324** [FriendsOfFlarum/best-answer#81]
## Bug Report

**Current Behavior**

fof/best-answer currently adds this css to the site: https://github.com/FriendsOfFlarum/best-answer/blob/master/resources/less/forum.less#L87-L88

```less
@media @desktop-up {
  .Post-header {
    & > ul {
      display: flex;
      flex-wrap: wrap;
    }
  }
}
```

this caused:

![image](https://github.com/FriendsOfFlarum/best-answer/assets/20221896/4872363a-a1ac-4b9c-9831-83af8a4e6faa)

and without that:

![image](https://github.com/FriendsOfFlarum/best-answer/assets/20221896/ab33ebba-7c2a-4d5d-9048-3afa971a95a4)

**Environment**
- Flarum version: 1.8.1
- Extension version: 1.3.1

Not sure whether that's intended behavior
